### ISSUE TITLE
cannot install touchdevelop package

### ISSUE THREAD

**Issue by grumpycoder100** [Microsoft/TouchDevelop#188]
starting shell watch...
copying touchdevelop.js to local folder...
starting with , pid: 8000
start, autoupdate=false
generating initial tdconfig.json
Deployment key: 77b12cc3ffea299543d0fbddc7ad4161f192f214
Editor URL: http://localhost:4242/editor/beta#td_deployment_key=77b12cc3ffea2995
43d0fbddc7ad4161f192f214
running: >start http://localhost:4242/editor/beta#td_deployment_key=77b12cc3ffea
299543d0fbddc7ad4161f192f214
exception (top): Error: write EPIPE
Error: write EPIPE
at exports._errnoException (util.js:746:11)
at Socket._writeGeneric (net.js:690:26)
at Socket._write (net.js:709:8)
at doWrite (streamwritable.js:301:12)
at writeOrBuffer (streamwritable.js:288:5)
at Socket.Writable.write (streamwritable.js:217:11)
at Socket.write (net.js:634:40)
at runCommand (C:\Users\ValuedAcerCustomer\Desktop\TD\tdserver.js:647:16)
at openUrl (C:\Users\ValuedAcerCustomer\Desktop\TD\tdserver.js:1894:9)
at startUp (C:\Users\ValuedAcerCustomer\Desktop\TD\tdserver.js:2233:13)
exception (top): Error: spawn cmd ENOENT
Error: spawn cmd ENOENT
at exports._errnoException (util.js:746:11)
at Process.ChildProcess.handle.onexit (childprocess.js:1053:32)
at child_process.js:1144:20
at process._tickCallback (node.js:355:11)

Help me!

**Comment by msprotz** [comment]
Which version of node are you using?

**Comment by grumpyspaceman** [comment]
The latest one. I'm not sure of the number I think its either v3.1 or something like that. But its the latest one.
