### ISSUE TITLE
TypeError in calculator

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/TouchDevelop#90]
````
TypeError: Cannot read property 'concat' of null
    at Calculator.getLocals (main.js:86636:36)
    at Calculator.findDefault (main.js:86639:55)
    at Calculator.insertProp (main.js:86854:49)
    at IntelliItem.onClick (main.js:100497:26)
    at CalcButton.fn [as _cb] (main.js:100559:23)
    at CalcButton.onClick (main.js:85174:22)
    at main.js:85161:80
    at ClickHandler.newCb [as f] (main.js:13585:28)
    at ClickHandler.fireClick (main.js:13538:22)
    at ClickHandler.handleEvent (main.js:13523:34)
````

**Comment by pelikhan** [comment]
https://www.touchdevelop.com/admin/crashes/-3/rank/6C77686E644D3247314579534E4D496D4C7A7348736E37436A70484E69594B6C4663567A656C7746376163253344?platform=js-2519757681283380000-f2bad37f.9b25.4ad4.2989.2e06ec43d5d1-80271

**Comment by mmoskal** [comment]
Peli, any idea how to repro that? It seems it occurs while the user is running the program while editing it in the calculator in some way.

**Comment by pelikhan** [comment]
Might be related to the issue that we sometimes continue to run after stopping the script (our #1 issue right now )

Sent from Outlook<http://taps.io/outlookmobile>




On Tue, Mar 17, 2015 at 3:29 PM -0700, "Micha³ Moskal" <notifications@github.com<mailto:notifications@github.com>> wrote:


Peli, any idea how to repro that? It seems it occurs while the user is running the program while editing it in the calculator in some way.

-

**Comment by mmoskal** [comment]
No repro.
