### ISSUE TITLE
assertion failed: rerun-isStopped

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/TouchDevelop#91]
````
Error: assertion failed: rerun-isStopped
    at Error (native)
    at Object.assert (main.js:9655:50)
    at Runtime.rerun (main.js:3292:23)
    at main.js:19911:28
    at ClickHandler.newCb [as f] (main.js:13585:28)
    at ClickHandler.fireClick (main.js:13538:22)
    at ClickHandler.handleEvent (main.js:13523:34)
````
https://www.touchdevelop.com/admin/crashes/-3/rank/7432426B734D2532423832695163742532427A5A4651754753637A6641386D6932547756425A4D75555735376F676F253344?platform=js-2519757681283380000-f2bad37f.9b25.4ad4.2989.2e06ec43d5d1-80271

**Comment by pelikhan** [comment]
fixed by 5bea0d2975a49ea0ca8e080505e2bdb1fb395460
